services:
  - type: web
    name: global-pay-backend
    env: node
    buildCommand: npm run install:backend
    startCommand: npm run start:backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: globalpay_super_secret_jwt_key_prod_2026
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FOREX_API_URL
        value: https://open.er-api.com/v6/latest
      - key: MONGO_URI
        value: mongodb+srv://globalpay:Password123!@cluster0.vyvtb7b.mongodb.net/globalpay?retryWrites=true&w=majority

  - type: static
    name: global-pay-frontend
    buildCommand: npm --prefix frontend install && npm --prefix frontend run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://global-pay-backend.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://global-pay-backend.onrender.com

